// Generated by scripts/taxonomy-build.mjs from data/taxonomy.yaml. Do not edit.
// Run `pnpm taxonomy` after changing the YAML.

export const TAXONOMY_HASH = "f78b7e6e0aa4c1ce";

export const TAXONOMY_DATA = {
  "version": 1,
  "facets": [
    {
      "key": "genre",
      "name": "Genre family",
      "multi": false,
      "note": "Single primary genre on the book; others as secondary tags"
    },
    {
      "key": "premise",
      "name": "Premise and setting",
      "multi": true
    },
    {
      "key": "activity",
      "name": "Activities and story structure",
      "multi": true
    },
    {
      "key": "protagonist",
      "name": "Protagonist",
      "multi": true
    },
    {
      "key": "class",
      "name": "Class archetype",
      "multi": true
    },
    {
      "key": "progression",
      "name": "Progression mechanics",
      "multi": true
    },
    {
      "key": "system_flavor",
      "name": "System flavor",
      "multi": true
    },
    {
      "key": "relationship",
      "name": "Relationships",
      "multi": true
    },
    {
      "key": "tone",
      "name": "Tone",
      "multi": true,
      "max": 3
    }
  ],
  "tags": [
    {
      "slug": "litrpg",
      "name": "LitRPG",
      "facet": "genre",
      "definition": "A visible game-like system with explicit mechanics (levels, stats, skills, notifications) shown on the page and important to the story",
      "include_when": "If mechanics are shown but light, it's still LitRPG, with crunch 1",
      "synonyms": [
        "lit rpg",
        "lit-rpg",
        "literary rpg"
      ],
      "status": "active"
    },
    {
      "slug": "gamelit",
      "name": "GameLit",
      "facet": "genre",
      "definition": "Game worlds, game logic or gaming culture without significant on-page mechanics",
      "include_when": "A story about playing games, or set in a game, with few status screens",
      "synonyms": [
        "game lit"
      ],
      "status": "active"
    },
    {
      "slug": "progression-fantasy",
      "name": "Progression Fantasy",
      "facet": "genre",
      "definition": "The protagonist's growth in power is the central throughline, with or without a visible system",
      "include_when": "No system shown → PF, not LitRPG (e.g. Cradle, Mother of Learning)",
      "synonyms": [
        "prog fantasy",
        "progfantasy",
        "pf"
      ],
      "status": "active"
    },
    {
      "slug": "cultivation",
      "name": "Cultivation",
      "facet": "genre",
      "definition": "Xianxia/wuxia-inspired advancement through realms, qi or spiritual energy, sects, techniques",
      "include_when": "A cultivation story with a visible system gets both `cultivation` and `litrpg` (e.g. Defiance of the Fall)",
      "synonyms": [
        "xianxia",
        "wuxia",
        "murim",
        "cultivator"
      ],
      "status": "active"
    },
    {
      "slug": "superhero-progression",
      "name": "Superhero Progression",
      "facet": "genre",
      "definition": "Powers, capes or hero academies, with growth as the throughline",
      "include_when": "e.g. Super Supportive",
      "synonyms": [
        "superhero",
        "capes",
        "super powers"
      ],
      "status": "active"
    },
    {
      "slug": "adjacent-fantasy",
      "name": "Adjacent Fantasy (borderline)",
      "facet": "genre",
      "definition": "Fantasy with strong magic-training or academy elements but no progression focus",
      "include_when": "Sets `in_scope = borderline`",
      "status": "active"
    },
    {
      "slug": "adjacent-scifi",
      "name": "Adjacent Sci-fi (borderline)",
      "facet": "genre",
      "definition": "Sci-fi with game or progression flavor but not centered on it",
      "include_when": "Sets `in_scope = borderline`",
      "status": "active"
    },
    {
      "slug": "system-apocalypse",
      "name": "System Apocalypse",
      "facet": "premise",
      "definition": "A System arrives on Earth (or a similar world), upending society; survival and leveling follow",
      "examples": "The Primal Hunter, Defiance of the Fall",
      "synonyms": [
        "apocalypse",
        "system integration apocalypse"
      ],
      "status": "active"
    },
    {
      "slug": "isekai",
      "name": "Isekai / Portal",
      "facet": "premise",
      "definition": "Protagonist is transported or reincarnated into another world",
      "examples": "He Who Fights With Monsters, Azarinth Healer",
      "synonyms": [
        "portal fantasy",
        "transported to another world",
        "summoned hero"
      ],
      "status": "active"
    },
    {
      "slug": "reincarnation",
      "name": "Reincarnation",
      "facet": "premise",
      "definition": "Protagonist is reborn, as a baby or into a new body, keeping memories",
      "examples": "Often co-tagged `isekai`",
      "synonyms": [
        "reborn",
        "rebirth",
        "transmigration"
      ],
      "status": "active"
    },
    {
      "slug": "regression",
      "name": "Regression / Second Chance",
      "facet": "premise",
      "definition": "Protagonist returns to an earlier point in their life with future knowledge",
      "examples": "Not a repeating loop (that's `time-loop`)",
      "synonyms": [
        "returner",
        "second chance",
        "do-over"
      ],
      "status": "active"
    },
    {
      "slug": "time-loop",
      "name": "Time Loop",
      "facet": "premise",
      "definition": "A period of time repeats and the protagonist retains knowledge across loops",
      "examples": "Mother of Learning",
      "synonyms": [
        "groundhog day",
        "loop"
      ],
      "status": "active"
    },
    {
      "slug": "vrmmo",
      "name": "VRMMO",
      "facet": "premise",
      "definition": "Full-dive virtual reality game that characters log in and out of",
      "synonyms": [
        "vrmmorpg",
        "virtual reality",
        "full dive",
        "mmorpg"
      ],
      "status": "active"
    },
    {
      "slug": "trapped-in-game",
      "name": "Trapped in a Game",
      "facet": "premise",
      "definition": "Characters can't log out; the game world is real stakes",
      "examples": "Sword Art Online-style",
      "synonyms": [
        "can't log out",
        "death game"
      ],
      "status": "active"
    },
    {
      "slug": "dungeon-crawler",
      "name": "Dungeon Crawler",
      "facet": "premise",
      "definition": "Clearing floors or levels of a dungeon is the core loop for the protagonist",
      "examples": "Dungeon Crawler Carl",
      "synonyms": [
        "dungeon crawl"
      ],
      "status": "active"
    },
    {
      "slug": "dungeon-core",
      "name": "Dungeon Core",
      "facet": "premise",
      "definition": "Protagonist *is*, or is bonded to, a dungeon and builds it, its monsters and traps",
      "examples": "Dungeon Born. Not the same as `dungeon-crawler`",
      "synonyms": [
        "dungeon master",
        "living dungeon"
      ],
      "status": "active"
    },
    {
      "slug": "tower-climbing",
      "name": "Tower Climbing",
      "facet": "premise",
      "definition": "Ascending floors or challenges of a tower",
      "examples": "Sufficiently Advanced Magic (the Spire)",
      "synonyms": [
        "tower",
        "spire"
      ],
      "status": "active"
    },
    {
      "slug": "gates-and-hunters",
      "name": "Gates & Hunters",
      "facet": "premise",
      "definition": "Portals or dungeons appear in a modern world; hunters or awakened fight them",
      "examples": "Solo Leveling-style",
      "synonyms": [
        "hunters",
        "gates",
        "awakened",
        "solo leveling"
      ],
      "status": "active"
    },
    {
      "slug": "academy",
      "name": "Academy / School",
      "facet": "premise",
      "definition": "Significant portion set at a school, academy or university of magic or combat",
      "examples": "Mark of the Fool",
      "synonyms": [
        "magic school",
        "magic academy",
        "school"
      ],
      "status": "active"
    },
    {
      "slug": "modern-earth",
      "name": "Modern Earth / Urban",
      "facet": "premise",
      "definition": "Set primarily in the contemporary real world",
      "synonyms": [
        "urban fantasy",
        "earth"
      ],
      "status": "active"
    },
    {
      "slug": "post-apocalyptic",
      "name": "Post-apocalyptic",
      "facet": "premise",
      "definition": "The world has already ended; rebuilding and scavenging",
      "status": "active"
    },
    {
      "slug": "space",
      "name": "Space / Sci-fi Setting",
      "facet": "premise",
      "definition": "Starships, planets, advanced technology",
      "synonyms": [
        "space opera",
        "sci-fi",
        "scifi"
      ],
      "status": "active"
    },
    {
      "slug": "cyberpunk",
      "name": "Cyberpunk",
      "facet": "premise",
      "definition": "High tech, low life, cybernetics, megacorps",
      "status": "active"
    },
    {
      "slug": "mythology",
      "name": "Gods & Mythology",
      "facet": "premise",
      "definition": "Pantheons, divine patrons and god-level stakes are central",
      "status": "active"
    },
    {
      "slug": "tutorial-world",
      "name": "Tutorial Arc",
      "facet": "premise",
      "definition": "A significant arc set in a System \"tutorial\" zone",
      "status": "active"
    },
    {
      "slug": "survival",
      "name": "Wilderness Survival",
      "facet": "premise",
      "definition": "Survival against the environment is a major focus",
      "status": "active"
    },
    {
      "slug": "military",
      "name": "Military",
      "facet": "premise",
      "definition": "Armies, ranks, campaigns and military life are central",
      "status": "active"
    },
    {
      "slug": "kingdom-building",
      "name": "Kingdom Building",
      "facet": "activity",
      "definition": "Ruling and growing a realm, city-state or nation, including policy, economy and armies",
      "synonyms": [
        "empire building",
        "kingdom builder",
        "4x"
      ],
      "status": "active"
    },
    {
      "slug": "settlement-building",
      "name": "Settlement / Town Building",
      "facet": "activity",
      "definition": "Founding and growing a village or town. Smaller scale than a kingdom",
      "synonyms": [
        "town building",
        "village building",
        "base builder"
      ],
      "status": "active"
    },
    {
      "slug": "base-building",
      "name": "Base Building",
      "facet": "activity",
      "definition": "Building and upgrading a personal base, stronghold or lair",
      "synonyms": [
        "stronghold"
      ],
      "status": "active"
    },
    {
      "slug": "crafting",
      "name": "Crafting",
      "facet": "activity",
      "definition": "Making items (smithing, enchanting, tailoring and so on) is a major activity",
      "synonyms": [
        "crafter",
        "blacksmithing",
        "smithing",
        "enchanting"
      ],
      "status": "active"
    },
    {
      "slug": "alchemy",
      "name": "Alchemy",
      "facet": "activity",
      "definition": "Potions, elixirs or pills as a main pursuit",
      "synonyms": [
        "potions",
        "pill refining"
      ],
      "status": "active"
    },
    {
      "slug": "cooking",
      "name": "Cooking",
      "facet": "activity",
      "definition": "Cooking is a major activity or source of power",
      "status": "active"
    },
    {
      "slug": "farming",
      "name": "Farming",
      "facet": "activity",
      "definition": "Agriculture, gardening or ranching is a major activity",
      "status": "active"
    },
    {
      "slug": "business",
      "name": "Business & Trade",
      "facet": "activity",
      "definition": "Shops, merchants, markets, companies, economic scheming",
      "synonyms": [
        "merchant",
        "shopkeeping",
        "shop",
        "trading"
      ],
      "status": "active"
    },
    {
      "slug": "monster-taming",
      "name": "Monster Taming",
      "facet": "activity",
      "definition": "Capturing, bonding or raising monsters or pets that fight alongside the MC",
      "synonyms": [
        "tamer",
        "monster tamer",
        "pets"
      ],
      "status": "active"
    },
    {
      "slug": "summoning",
      "name": "Summoning",
      "facet": "activity",
      "definition": "Summoned creatures or minions are a core fighting style",
      "synonyms": [
        "summoner",
        "minions"
      ],
      "status": "active"
    },
    {
      "slug": "necromancy",
      "name": "Necromancy",
      "facet": "activity",
      "definition": "Raising or commanding the undead is a core power",
      "synonyms": [
        "necromancer",
        "undead"
      ],
      "status": "active"
    },
    {
      "slug": "deckbuilding",
      "name": "Deckbuilding / Cards",
      "facet": "activity",
      "definition": "Power system built on cards or decks",
      "synonyms": [
        "cards",
        "card game"
      ],
      "status": "active"
    },
    {
      "slug": "tournament",
      "name": "Tournaments",
      "facet": "activity",
      "definition": "Structured competitions are major arcs",
      "status": "active"
    },
    {
      "slug": "war",
      "name": "War & Battles",
      "facet": "activity",
      "definition": "Large-scale warfare, sieges and campaigns",
      "status": "active"
    },
    {
      "slug": "politics",
      "name": "Politics & Intrigue",
      "facet": "activity",
      "definition": "Factions, scheming and courtly maneuvering are major threads",
      "synonyms": [
        "intrigue",
        "court politics"
      ],
      "status": "active"
    },
    {
      "slug": "exploration",
      "name": "Exploration",
      "facet": "activity",
      "definition": "Discovering new lands, ruins or a world's secrets drives the plot",
      "status": "active"
    },
    {
      "slug": "guild-building",
      "name": "Guild / Sect Building",
      "facet": "activity",
      "definition": "Founding and running a guild, sect, company or adventuring organization",
      "synonyms": [
        "sect building",
        "guild master"
      ],
      "status": "active"
    },
    {
      "slug": "build-crafting",
      "name": "Build Optimization",
      "facet": "activity",
      "definition": "The protagonist deliberately theorizes and optimizes their build or skill synergies",
      "synonyms": [
        "min-maxing",
        "theorycrafting",
        "build optimization"
      ],
      "status": "active"
    },
    {
      "slug": "system-exploitation",
      "name": "System Exploitation",
      "facet": "activity",
      "definition": "Finding loopholes, bugs or unintended uses of the System",
      "synonyms": [
        "exploits",
        "loopholes",
        "bug abuse"
      ],
      "status": "active"
    },
    {
      "slug": "questing",
      "name": "Questing",
      "facet": "activity",
      "definition": "Episodic quests and adventures are the main structure",
      "status": "active"
    },
    {
      "slug": "heist",
      "name": "Heists",
      "facet": "activity",
      "definition": "Planned infiltration and theft capers are major arcs",
      "status": "active"
    },
    {
      "slug": "teaching",
      "name": "Teaching / Mentorship",
      "facet": "activity",
      "definition": "The protagonist trains or mentors others as a major thread",
      "status": "active"
    },
    {
      "slug": "revenge",
      "name": "Revenge Arc",
      "facet": "activity",
      "definition": "Getting even with those who wronged the MC drives a major arc",
      "status": "active"
    },
    {
      "slug": "face-slapping",
      "name": "Face-slapping",
      "facet": "activity",
      "definition": "Arrogant enemies underestimate the MC and are humbled (a cultivation staple; some readers love it, some avoid it)",
      "synonyms": [
        "face slap"
      ],
      "commonly_excluded": true,
      "status": "active"
    },
    {
      "slug": "male-mc",
      "name": "Male MC",
      "facet": "protagonist",
      "definition": "Primary protagonist is male",
      "synonyms": [
        "male lead",
        "male protagonist"
      ],
      "status": "active"
    },
    {
      "slug": "female-mc",
      "name": "Female MC",
      "facet": "protagonist",
      "definition": "Primary protagonist is female",
      "examples": "Azarinth Healer",
      "synonyms": [
        "female lead",
        "female protagonist"
      ],
      "status": "active"
    },
    {
      "slug": "nonhuman-mc",
      "name": "Non-human MC",
      "facet": "protagonist",
      "definition": "Protagonist is not human: monster, dungeon, object, tree, AI, animal",
      "synonyms": [
        "non-human lead"
      ],
      "status": "active"
    },
    {
      "slug": "monster-mc",
      "name": "Monster MC / Evolution",
      "facet": "protagonist",
      "definition": "Protagonist is a monster who grows by evolving",
      "examples": "Chrysalis",
      "synonyms": [
        "monster evolution",
        "evolution"
      ],
      "status": "active"
    },
    {
      "slug": "villain-mc",
      "name": "Villain / Antihero MC",
      "facet": "protagonist",
      "definition": "Protagonist is morally dark, a villain, or chooses \"evil\" paths",
      "synonyms": [
        "evil mc",
        "antihero",
        "anti-hero"
      ],
      "commonly_excluded": true,
      "status": "active"
    },
    {
      "slug": "npc-mc",
      "name": "NPC MC",
      "facet": "protagonist",
      "definition": "Protagonist is a game NPC",
      "status": "active"
    },
    {
      "slug": "multiple-pov",
      "name": "Multiple POV",
      "facet": "protagonist",
      "definition": "Several significant point-of-view characters",
      "commonly_excluded": true,
      "status": "active"
    },
    {
      "slug": "solo-mc",
      "name": "Solo MC",
      "facet": "protagonist",
      "definition": "Protagonist mostly fights and progresses alone",
      "status": "active"
    },
    {
      "slug": "party-focused",
      "name": "Party / Team Focus",
      "facet": "protagonist",
      "definition": "A stable party or team is central",
      "status": "active"
    },
    {
      "slug": "clever-mc",
      "name": "Clever / Genius MC",
      "facet": "protagonist",
      "definition": "Wins mainly through intelligence, planning or knowledge",
      "synonyms": [
        "smart mc",
        "genius mc"
      ],
      "status": "active"
    },
    {
      "slug": "op-mc",
      "name": "Overpowered MC",
      "facet": "protagonist",
      "definition": "Protagonist is far stronger than peers early on",
      "synonyms": [
        "overpowered",
        "op protagonist"
      ],
      "commonly_excluded": true,
      "status": "active"
    },
    {
      "slug": "weak-to-strong",
      "name": "Weak to Strong",
      "facet": "protagonist",
      "definition": "Starts notably weak or disadvantaged and climbs",
      "synonyms": [
        "zero to hero",
        "underdog"
      ],
      "status": "active"
    },
    {
      "slug": "older-mc",
      "name": "Adult / Older MC",
      "facet": "protagonist",
      "definition": "Protagonist is middle-aged or older",
      "status": "active"
    },
    {
      "slug": "young-mc",
      "name": "Teen MC",
      "facet": "protagonist",
      "definition": "Protagonist is a teenager for most of the book",
      "commonly_excluded": true,
      "status": "active"
    },
    {
      "slug": "support-class-mc",
      "name": "Support / Non-combat Class",
      "facet": "protagonist",
      "definition": "Healer, crafter, buffer or other non-frontline role",
      "synonyms": [
        "non-combat class",
        "support class"
      ],
      "status": "active"
    },
    {
      "slug": "gamer-mc",
      "name": "Gamer MC",
      "facet": "protagonist",
      "definition": "Protagonist is a gamer and uses real game knowledge or instincts to get ahead",
      "synonyms": [
        "gamer"
      ],
      "status": "active"
    },
    {
      "slug": "cheat-ability",
      "name": "Cheat Ability",
      "facet": "protagonist",
      "definition": "Protagonist has a unique, rule-breaking advantage no one else has (common in isekai)",
      "synonyms": [
        "cheat",
        "cheat skill",
        "unique skill"
      ],
      "status": "active"
    },
    {
      "slug": "class-mage",
      "name": "Mage",
      "facet": "class",
      "definition": "The protagonist's main class casts spells (mage, wizard, sorcerer, elementalist)",
      "status": "active"
    },
    {
      "slug": "class-warrior",
      "name": "Warrior",
      "facet": "class",
      "definition": "The protagonist's main class is a melee fighter (warrior, fighter, swordsman, berserker)",
      "status": "active"
    },
    {
      "slug": "class-rogue",
      "name": "Rogue / Assassin",
      "facet": "class",
      "definition": "The protagonist's main class relies on stealth and precision (rogue, thief, assassin)",
      "status": "active"
    },
    {
      "slug": "class-ranger",
      "name": "Ranger / Archer",
      "facet": "class",
      "definition": "The protagonist's main class fights at range or in the wild (ranger, archer, hunter)",
      "status": "active"
    },
    {
      "slug": "class-healer",
      "name": "Healer",
      "facet": "class",
      "definition": "The protagonist's main class heals and supports (healer, cleric, priest)",
      "status": "active"
    },
    {
      "slug": "class-tank",
      "name": "Tank",
      "facet": "class",
      "definition": "The protagonist's main class absorbs damage and protects the party (tank, guardian, paladin)",
      "status": "active"
    },
    {
      "slug": "class-necromancer",
      "name": "Necromancer",
      "facet": "class",
      "definition": "The protagonist's main class commands death magic or the undead",
      "status": "active"
    },
    {
      "slug": "class-summoner",
      "name": "Summoner",
      "facet": "class",
      "definition": "The protagonist's main class summons creatures or spirits to fight",
      "status": "active"
    },
    {
      "slug": "class-tamer",
      "name": "Tamer",
      "facet": "class",
      "definition": "The protagonist's main class bonds with and commands monsters or beasts",
      "status": "active"
    },
    {
      "slug": "class-crafter",
      "name": "Crafter",
      "facet": "class",
      "definition": "The protagonist's main class makes things (smith, enchanter, alchemist, artificer)",
      "status": "active"
    },
    {
      "slug": "class-unique",
      "name": "Unique Class",
      "facet": "class",
      "definition": "The protagonist has a unique or hybrid class, and that uniqueness is a plot point",
      "status": "active"
    },
    {
      "slug": "levels",
      "name": "Levels",
      "facet": "progression",
      "definition": "Numbered levels are tracked",
      "status": "active"
    },
    {
      "slug": "classes",
      "name": "Classes",
      "facet": "progression",
      "definition": "Characters have classes or jobs",
      "status": "active"
    },
    {
      "slug": "skills",
      "name": "Skills",
      "facet": "progression",
      "definition": "Discrete, named skills or abilities are acquired and leveled",
      "status": "active"
    },
    {
      "slug": "stats",
      "name": "Stats / Attributes",
      "facet": "progression",
      "definition": "Numeric attributes (STR, AGI, and so on) are tracked",
      "status": "active"
    },
    {
      "slug": "titles-achievements",
      "name": "Titles & Achievements",
      "facet": "progression",
      "definition": "Titles or achievements grant effects",
      "status": "active"
    },
    {
      "slug": "class-evolution",
      "name": "Class Evolution",
      "facet": "progression",
      "definition": "Classes upgrade or evolve at thresholds",
      "status": "active"
    },
    {
      "slug": "race-evolution",
      "name": "Race / Species Evolution",
      "facet": "progression",
      "definition": "The protagonist's race or species evolves",
      "synonyms": [
        "species evolution"
      ],
      "status": "active"
    },
    {
      "slug": "skill-fusion",
      "name": "Skill Fusion",
      "facet": "progression",
      "definition": "Skills combine into new skills",
      "status": "active"
    },
    {
      "slug": "skill-absorption",
      "name": "Skill Stealing / Absorption",
      "facet": "progression",
      "definition": "Taking skills or powers from others or from defeated enemies",
      "synonyms": [
        "skill stealing",
        "absorption"
      ],
      "status": "active"
    },
    {
      "slug": "cultivation-realms",
      "name": "Cultivation Realms",
      "facet": "progression",
      "definition": "Advancement through named realms or stages",
      "synonyms": [
        "realms",
        "qi"
      ],
      "status": "active"
    },
    {
      "slug": "ranks-tiers",
      "name": "Ranks / Tiers",
      "facet": "progression",
      "definition": "Named tiers of power without full cultivation trappings",
      "examples": "Copper → Iron → Jade",
      "synonyms": [
        "tiers",
        "ranks"
      ],
      "status": "active"
    },
    {
      "slug": "mana-core",
      "name": "Mana Core",
      "facet": "progression",
      "definition": "A core or center of magical power that is refined and advanced",
      "status": "active"
    },
    {
      "slug": "loot",
      "name": "Loot & Gear",
      "facet": "progression",
      "definition": "Equipment drops and gear upgrades matter",
      "synonyms": [
        "gear",
        "equipment"
      ],
      "status": "active"
    },
    {
      "slug": "bloodline",
      "name": "Bloodlines",
      "facet": "progression",
      "definition": "Inherited powers or bloodline awakening",
      "status": "active"
    },
    {
      "slug": "companions-progression",
      "name": "Companion Progression",
      "facet": "progression",
      "definition": "Pets, summons or companions level up alongside the MC",
      "status": "active"
    },
    {
      "slug": "respawn",
      "name": "Respawn / Death Mechanics",
      "facet": "progression",
      "definition": "Death has game-like rules (respawn, penalties)",
      "status": "active"
    },
    {
      "slug": "training-arcs",
      "name": "Training Arcs",
      "facet": "progression",
      "definition": "Significant page time on deliberate training and practice",
      "status": "active"
    },
    {
      "slug": "snarky-system",
      "name": "Snarky / Sentient System",
      "facet": "system_flavor",
      "definition": "The System, an AI or an announcer has a personality, often sarcastic, and is a character in its own right",
      "synonyms": [
        "sentient system",
        "system ai",
        "announcer"
      ],
      "status": "active"
    },
    {
      "slug": "system-mystery",
      "name": "System Mystery",
      "facet": "system_flavor",
      "definition": "Who made the System, and why, is a central mystery the story digs into",
      "status": "active"
    },
    {
      "slug": "hidden-system",
      "name": "Hidden System",
      "facet": "system_flavor",
      "definition": "Only the MC (or a few people) can see or use the System",
      "synonyms": [
        "secret system"
      ],
      "status": "active"
    },
    {
      "slug": "system-integration",
      "name": "Integration Event",
      "facet": "system_flavor",
      "definition": "The story shows the System arriving and society reacting (often with `system-apocalypse`)",
      "status": "active"
    },
    {
      "slug": "found-family",
      "name": "Found Family",
      "facet": "relationship",
      "definition": "Characters who aren't related become a family",
      "synonyms": [
        "found-family"
      ],
      "status": "active"
    },
    {
      "slug": "slow-burn",
      "name": "Slow-burn Romance",
      "facet": "relationship",
      "definition": "A romance that builds slowly over many chapters or books",
      "status": "active"
    },
    {
      "slug": "lgbtq-characters",
      "name": "LGBTQ+ Characters",
      "facet": "relationship",
      "definition": "Significant LGBTQ+ characters",
      "status": "active"
    },
    {
      "slug": "lgbtq-romance",
      "name": "LGBTQ+ Romance",
      "facet": "relationship",
      "definition": "A queer romantic relationship is part of the story",
      "status": "active"
    },
    {
      "slug": "animal-companion",
      "name": "Animal Companion",
      "facet": "relationship",
      "definition": "A loyal animal or pet companion travels with the MC",
      "status": "active"
    },
    {
      "slug": "humorous",
      "name": "Humorous",
      "facet": "tone",
      "definition": "Comedy is a primary feature",
      "examples": "Dungeon Crawler Carl",
      "synonyms": [
        "comedy",
        "funny"
      ],
      "status": "active"
    },
    {
      "slug": "dark-humor",
      "name": "Dark Humor",
      "facet": "tone",
      "definition": "Comedy that plays with violence, bleakness or absurdity",
      "synonyms": [
        "black comedy"
      ],
      "status": "active"
    },
    {
      "slug": "cozy",
      "name": "Cozy",
      "facet": "tone",
      "definition": "Low stakes, comfort-focused, warm",
      "examples": "Beware of Chicken",
      "synonyms": [
        "cosy",
        "low stakes",
        "comfy"
      ],
      "status": "active"
    },
    {
      "slug": "slice-of-life",
      "name": "Slice of Life",
      "facet": "tone",
      "definition": "Everyday life and small moments get significant page time",
      "examples": "The Wandering Inn",
      "synonyms": [
        "sol"
      ],
      "commonly_excluded": true,
      "status": "active"
    },
    {
      "slug": "lighthearted",
      "name": "Lighthearted",
      "facet": "tone",
      "definition": "Generally upbeat, without being primarily comedy",
      "status": "active"
    },
    {
      "slug": "heroic",
      "name": "Heroic / Noblebright",
      "facet": "tone",
      "definition": "Good people doing good. Hopeful",
      "synonyms": [
        "noblebright",
        "hopeful"
      ],
      "status": "active"
    },
    {
      "slug": "serious-epic",
      "name": "Serious / Epic",
      "facet": "tone",
      "definition": "High stakes, earnest, sweeping",
      "status": "active"
    },
    {
      "slug": "grimdark",
      "name": "Grimdark",
      "facet": "tone",
      "definition": "Bleak world, morally gray-to-black, heavy consequences",
      "synonyms": [
        "dark fantasy"
      ],
      "commonly_excluded": true,
      "status": "active"
    },
    {
      "slug": "satire",
      "name": "Satire / Parody",
      "facet": "tone",
      "definition": "Mocks the genre, games or society",
      "synonyms": [
        "parody"
      ],
      "status": "active"
    },
    {
      "slug": "horror",
      "name": "Horror",
      "facet": "tone",
      "definition": "Dread, body horror or horror set pieces are central",
      "commonly_excluded": true,
      "status": "active"
    },
    {
      "slug": "philosophical",
      "name": "Philosophical",
      "facet": "tone",
      "definition": "Explores ideas (identity, ethics, meaning) as a major thread",
      "status": "active"
    }
  ],
  "crunch_levels": [
    {
      "value": 0,
      "label": "No visible system",
      "signals": "No status screens or notifications. Progression is described narratively"
    },
    {
      "value": 1,
      "label": "Light",
      "signals": "Occasional notifications or level mentions. Rare or short status screens"
    },
    {
      "value": 2,
      "label": "Medium",
      "signals": "Regular status screens and skill descriptions. Numbers matter but don't dominate"
    },
    {
      "value": 3,
      "label": "Heavy",
      "signals": "Frequent full stat blocks, tables, math, build theory. Readers are expected to engage with numbers (e.g. Delve)"
    }
  ],
  "romance_levels": [
    {
      "value": 0,
      "label": "None",
      "signals": "No romantic plotline"
    },
    {
      "value": 1,
      "label": "Hints",
      "signals": "Flirting or attraction, no relationship"
    },
    {
      "value": 2,
      "label": "Subplot",
      "signals": "A relationship exists but takes little page time"
    },
    {
      "value": 3,
      "label": "Significant",
      "signals": "Relationship development is a major thread"
    },
    {
      "value": 4,
      "label": "Central",
      "signals": "Romance is co-equal with progression (romantasy-LitRPG)"
    }
  ],
  "harem": [
    {
      "value": "none",
      "definition": "One romantic partner at a time, or none"
    },
    {
      "value": "implied",
      "definition": "Multiple love interests are teased or set up, but no committed multi-partner relationship yet"
    },
    {
      "value": "harem",
      "definition": "The (usually male) protagonist has committed or ongoing relationships with multiple partners"
    },
    {
      "value": "reverse_harem",
      "definition": "A (usually female) protagonist has committed or ongoing relationships with multiple partners"
    }
  ],
  "content_flags": [
    {
      "slug": "explicit-sex",
      "name": "Explicit sexual content",
      "definition": "On-page sex described explicitly (not fade-to-black)"
    },
    {
      "slug": "graphic-violence",
      "name": "Graphic violence",
      "definition": "Violence described in vivid, sustained detail"
    },
    {
      "slug": "gore",
      "name": "Gore / body horror",
      "definition": "Graphic injury, dismemberment, body horror"
    },
    {
      "slug": "sexual-violence",
      "name": "Sexual violence",
      "definition": "Depicted or explicitly referenced sexual assault"
    },
    {
      "slug": "torture",
      "name": "Torture",
      "definition": "On-page torture"
    },
    {
      "slug": "self-harm",
      "name": "Self-harm / suicide",
      "definition": "Depicted or significantly discussed"
    },
    {
      "slug": "heavy-profanity",
      "name": "Heavy profanity",
      "definition": "Pervasive strong language"
    },
    {
      "slug": "substance-abuse",
      "name": "Substance abuse",
      "definition": "Significant depiction of addiction or drug abuse"
    }
  ],
  "ai_attestation": [
    "human",
    "ai_assisted",
    "ai_generated",
    "unknown"
  ],
  "dials": [
    {
      "key": "pacing",
      "anchors": {
        "0": "Lingers: long stretches of downtime, introspection or slice of life",
        "5": "A balanced mix of action and downtime",
        "10": "Relentless: action and escalation nearly every chapter"
      },
      "name": "Pacing"
    },
    {
      "key": "tone",
      "anchors": {
        "0": "Bleak: cruelty, loss, hopelessness",
        "5": "A mix of light and dark",
        "10": "Warm and hopeful throughout"
      },
      "name": "Tone"
    },
    {
      "key": "humor",
      "anchors": {
        "0": "Played completely straight",
        "5": "Regular banter and jokes",
        "10": "Comedy is the point"
      },
      "name": "Humor"
    },
    {
      "key": "crunch",
      "anchors": {
        "0": "No visible system",
        "5": "Regular status screens; numbers matter sometimes",
        "10": "Frequent full stat blocks, tables and build math"
      },
      "name": "Crunch"
    },
    {
      "key": "progression_speed",
      "anchors": {
        "0": "Painfully slow, hard-won gains",
        "5": "Steady, visible growth",
        "10": "Rapid, highly visible growth"
      },
      "name": "Progression speed"
    },
    {
      "key": "power_fantasy",
      "anchors": {
        "0": "Underdog, outmatched most of the time",
        "5": "Strong, but challenged",
        "10": "Godmode: dominates nearly everyone"
      },
      "name": "Power fantasy"
    },
    {
      "key": "rigour",
      "anchors": {
        "0": "Loose, flavorful system; rule of cool beats rules",
        "5": "Rules matter but bend",
        "10": "Hard rules; exact mechanics drive the plot"
      },
      "name": "System rigour"
    },
    {
      "key": "combat",
      "anchors": {
        "0": "Almost no fighting: crafting, building, business or daily life",
        "5": "Half fighting, half other activities",
        "10": "Fight after fight"
      },
      "name": "Combat"
    },
    {
      "key": "scope",
      "anchors": {
        "0": "Personal stakes: a village, a family, a shop",
        "5": "Regional or national stakes",
        "10": "World-ending or cosmic stakes"
      },
      "name": "Scope"
    },
    {
      "key": "ensemble",
      "anchors": {
        "0": "Lone wolf; others barely matter",
        "5": "MC-focused, with a regular supporting cast",
        "10": "The party, team or found family is the heart of the story"
      },
      "name": "Ensemble"
    },
    {
      "key": "lore",
      "anchors": {
        "0": "The setting is a light backdrop",
        "5": "Solid worldbuilding that matters sometimes",
        "10": "Deep lore, history and mysteries drive the plot"
      },
      "name": "Lore"
    },
    {
      "key": "morality",
      "anchors": {
        "0": "Selfless hero",
        "5": "Pragmatic, gray choices",
        "10": "Ruthless or outright villainous"
      },
      "name": "Morality"
    },
    {
      "key": "strategy",
      "anchors": {
        "0": "Wins on instinct and raw power",
        "5": "Some planning and clever tricks",
        "10": "Planning, min-maxing and system exploits are central"
      },
      "name": "Strategy"
    },
    {
      "key": "prose",
      "anchors": {
        "0": "Lean, straightforward, fast to read",
        "5": "Clear, with some description",
        "10": "Rich, descriptive, wordy"
      },
      "name": "Prose"
    },
    {
      "key": "danger",
      "anchors": {
        "0": "Thick plot armor, cozy safety",
        "5": "Real danger, occasional losses",
        "10": "Anyone can die, and losses stick"
      },
      "name": "Danger"
    },
    {
      "key": "plot_structure",
      "anchors": {
        "0": "Episodic, serial-style adventures",
        "5": "Arcs with some side episodes",
        "10": "Tightly plotted arcs"
      },
      "name": "Plot structure"
    },
    {
      "key": "romance",
      "anchors": {
        "0": "None",
        "5": "A real subplot",
        "10": "Romance is central"
      },
      "name": "Romance"
    }
  ],
  "stats": [
    {
      "key": "competent_mc",
      "name": "Competent MC",
      "type": "judgment",
      "anchors": {
        "0": "Baffling decisions; the plot depends on the MC being dumb",
        "5": "Usually sensible, with some frustrating choices",
        "10": "Consistently sharp; learns from mistakes; no idiot ball"
      }
    },
    {
      "key": "rule_of_cool",
      "name": "Rule of Cool",
      "type": "descriptive",
      "anchors": {
        "0": "Mundane abilities and set pieces",
        "5": "Regular cool moments",
        "10": "Constant \"hell yes\" abilities, gear and spectacle"
      }
    },
    {
      "key": "number_go_up",
      "name": "Number Go Up",
      "type": "descriptive",
      "anchors": {
        "0": "Progression is rare or vague",
        "5": "A satisfying gain every few chapters",
        "10": "Frequent, tangible, satisfying gains"
      }
    },
    {
      "key": "build_payoff",
      "name": "Build Payoff",
      "type": "descriptive",
      "anchors": {
        "0": "Choices about skills, stats or classes don't matter",
        "5": "Some choices matter",
        "10": "Build choices are meaningful, clever and pay off"
      }
    },
    {
      "key": "earned_power",
      "name": "Earned Power",
      "type": "judgment",
      "anchors": {
        "0": "Frequent handouts and ass-pulls",
        "5": "Mostly earned, with some lucky breaks",
        "10": "Every gain earned through effort, risk or cleverness"
      }
    },
    {
      "key": "system_consistency",
      "name": "Consistent System",
      "type": "judgment",
      "anchors": {
        "0": "Rules and numbers contradict themselves",
        "5": "Minor slips",
        "10": "Airtight; the author respects the system's logic"
      }
    },
    {
      "key": "hype",
      "name": "Hype Moments",
      "type": "judgment",
      "anchors": {
        "0": "Flat",
        "5": "Some satisfying payoffs",
        "10": "Cathartic wins, setups that land, arrogant foes humbled"
      }
    },
    {
      "key": "low_drama",
      "name": "Low Drama",
      "type": "judgment",
      "anchors": {
        "0": "Constant manufactured conflict and misunderstandings",
        "5": "Some interpersonal friction",
        "10": "Drama-free; conflict comes from the plot, not pettiness"
      }
    },
    {
      "key": "party_chemistry",
      "name": "Party Chemistry",
      "type": "judgment",
      "anchors": {
        "0": "Flat or annoying companions",
        "5": "Likable companions",
        "10": "Banter, trust and found family that work"
      }
    },
    {
      "key": "rootable_mc",
      "name": "Rootable MC",
      "type": "judgment",
      "anchors": {
        "0": "Hard to root for",
        "5": "Mixed",
        "10": "Firmly in their corner (villain MCs can score high)"
      }
    },
    {
      "key": "fast_start",
      "name": "Fast Start",
      "type": "descriptive",
      "anchors": {
        "0": "Long slow intro; the system arrives very late",
        "5": "Progression starts within the first act",
        "10": "Hooks on page one; progression starts immediately"
      }
    },
    {
      "key": "satisfying_endings",
      "name": "Satisfying Endings",
      "type": "descriptive",
      "anchors": {
        "0": "Every book ends on a cliffhanger",
        "5": "Main arc mostly resolved, with a hook",
        "10": "Each book resolves its main arc"
      }
    }
  ]
} as const;
